apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-back
spec:
  replicas: 3 # Número de réplicas
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: voting-back
  template:
    metadata:
      labels:
        app: voting-back
    spec:
      containers:
          - name: voting-back
            image: brosgarc/voting-back
            ports:
            - containerPort: 8080
            env:
              - name: MONGODB_URI
                value: "mongodb://voting-db:27017" 
              - name: PORT
                value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: voting-back
spec:
  selector:
    app: voting-back
  ports:
    - protocol: TCP
      port: 8080 
      targetPort: 8080 
  type: LoadBalancer # O ClusterIP