apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-db
spec:
  replicas: 1 # Número de réplicas
  selector:
    matchLabels:
      app: voting-db
  template:
    metadata:
      labels:
        app: voting-db
    spec:
      containers:
          - name: voting-db
            image: mongo:latest
            ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: voting-db
spec:
  selector:
    app: voting-db # Debe coincidir con el selector del Deployment
  ports:
    - protocol: TCP
      port: 27017 # Puerto del servicio (el mismo que el puerto del contenedor)
      targetPort: 27017 # Puerto del contenedor