version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: voting-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - voting-network

  # Backend API service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: voting-backend
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - PORT=8080
      # APM configuration (optional)
      - APM_SERVER_URL=${APM_SERVER_URL:-}
      - APM_SERVICE_NAME=voting-platform-backend
      - APM_ENVIRONMENT=development
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - voting-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: voting-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api/v1
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - voting-network

networks:
  voting-network:
    driver: bridge

volumes:
  mongodb_data: